/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YT4Hhnr1cwK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link"
import { BubbleChat } from 'flowise-embed-react'
const config = require('../config.json') // Assuming config.json is in the same directory


export function IndustryUi() {
  return (
    <div className="flex flex-col items-center justify-center h-[70vh]">
      <div className="space-y-4 text-center">
        <h1 className="text-3xl font-bold">Industry Specfic Knowledge Base</h1>
        <p className="text-lg">Discover the Production Incentives.</p>
        <Link
          href="/"
          className="inline-flex items-center justify-center px-6 py-3 text-sm font-medium text-white bg-primary rounded-md shadow-sm transition-colors hover:bg-primary-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"
          prefetch={false}
        >
          Home
        </Link>&nbsp;&nbsp;
      </div>
      <BubbleChat chatflowid={config.industryChatflowId} apiHost="https://flowise-g57j.onrender.com" />
    </div>
  )
}
