source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'sqlite3'
gem 'therubyracer', '>= 0.8.2'
gem 'jquery-rails'
gem 'itslog'
gem 'exception_notification'
gem 'letter_opener'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rails-footnotes', '>= 3.7.5.rc4'
end

